apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fitwyf4xi-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-quarkus:b71bdda746d521441fa3b18959f656abe2a68108@sha256:4c2c248599fe35336b173dbaf0e7dee9881b46eb0e0d043884ff67356953d733
          name: container-image
